CREATE TABLE TB_LED(
    ID_LED INTEGER AUTO_INCREMENT NOT NULL,
    POTENCIA INT,
    PRIMARY KEY(ID_LED)
);

CREATE TABLE TB_FATO_LED(
    ID_FATO_LED INTEGER AUTO_INCREMENT NOT NULL,
    DT_INICIO DATETIME,
    DT_FIM DATETIME,
    INTERVALO_TEMPO DATETIME,
    ID_LED INT,
    CONSUMO INT,
    VALOR DECIMAL(10,2),
    PRIMARY KEY(ID_FATO_LED),
    FOREIGN KEY(ID_LED) REFERENCES TB_LED(ID_LED)
);